import os

VariantDir('out', './', duplicate=0)
env = Environment(  ENV = os.environ,
                    tools = ['mingw'],
                    CC='arm-none-eabi-gcc',
                    CXX='arm-none-eabi-g++',
                    AS='arm-none-eabi-as',
                    OBJDUMP='arm-none-eabi-objdump',
                    OBJCOPY='arm-none-eabi-objcopy',
                    LINKFLAGS=' --specs=nano.specs -ggdb -Wl,-Map=out/program.map,-Tlinker.ld',
                    CFLAGS=' -ggdb ')

source = ['out/main.cpp', 'out/startup.s' ]

program = env.Program('program', source)
env.Clean(program, 'program.map')

